# Site settings
title: Otis Blog
email: altispec@gmail.com
description: "Thoughts on Ruby, Javascript, CSS, Design and more..."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://otischou.tw" # the base hostname & protocol for your site
twitter_username:
github_username:  AnNOtis

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

future: true

collections:
  imperfect:
    label: imperfect
    description: 生人勿近
    permalink: /imperfect/:path/
    output: true
